<?php

/**
 * @file
 * Block Entity
 */


/**
 * Implements hook_block_info().
 */
function nissan_block_info() {
  $blocks['galeria'] = array(
    'info' => t('Galeria'),
    'cache' => DRUPAL_NO_CACHE
  );
  return $blocks;
}


/**
 * Implements hook_theme().
 */
function nissan_theme($existing, $type, $theme, $path) {
 if($type == 'module'){
    return array(
      'nissan_template' => array(
        'variables' => array('var_name'=>NULL),
        'template' => 'templates/real_gallery_videos'
      ),
    );
  }
  return array(); 
}


/**
 * Implements hook_block_view().
 */
function nissan_block_view($delta = '') {
  $block = array();
	 switch ($delta) {
	    case 'galeria':
     Global $user; 
	   if (get_sids() != FALSE && $user->uid == TRUE) {
        $block['subject'] = t('Galería');
     }
		 $block['content'] = theme('nissan_template', array('1' =>'1'));
		 break;
	 }
  return $block;
}


/**
 * Implements hook_init().
 */

function nissan_init() {
   Global $base_url;
   drupal_add_js(array('nissan' => array('dominio' => $base_url)), array('type' => 'setting'));
   drupal_add_js(drupal_get_path('module', 'nissan') . '/js/redirect.js');
}

/**
 * Implements hook_webform().
 */

function nissan_webform_submission_presave($node, &$submission) {
  if (!empty($submission->data[2][0])) {
       $file = file_load($submission->file_usage['added_fids'][0]);
       $ext = pathinfo($file->filename, PATHINFO_EXTENSION);
       if ($ext != 'mp4') {
              file_save($file);
              $file = file_load($submission->file_usage['added_fids'][0]);
              $path = str_replace(" ", "\\ ", drupal_realpath($file->uri));
              shell_exec("/usr/bin/ffmpeg  -i ".$path." -strict -2 ".$path.".mp4");
              $file->filename = $file->filename . '.mp4';
              $file->uri =  $file->uri.'.mp4';
              $path_url = file_create_url($file->uri);
              created_node_video($path_url);
              file_save($file);
        }else{
              $path_url = file_create_url($file->uri);
              created_node_video($path_url);   
        } 
  }else{
         ctools_include('ajax'); ctools_add_js('ajax-responder');
         $commands[] = ctools_ajax_command_redirect('gracias');
         print ajax_render($commands);
         exit;
  }
}

function get_sids(){
      // Query videos Aprovados.
    $result = db_select('webform_submitted_data', 'c')
             ->condition('cid', 41, '=') 
             ->fields('c') 
             ->execute()
             ->fetchAll();


      $sids  = '';     
      foreach ($result as $key => $value) {
        if ($value->data == true) {
           $sids .= $value->sid . "+";
        }
      }
    
      $cadena = $sids;
      if (substr($cadena, -1) == '+') {
        $sids = substr($cadena, 0, -1);
      }
      $view = views_get_view('nissan_galeria');
      $view->set_display("page");
      $view->set_arguments(array($sids));
      $view->pre_execute();
      $view->execute(); 

      module_load_include('inc', 'webform', 'includes/webform.submissions'); 
      $count = count($view->result); 

   return $count;   
}

function created_node_video($path_url){
   $sid = '';
   $result = db_select('webform_submitted_data', 'c')
             ->condition('cid', 41, '=') 
             ->fields('c')
             ->orderBy("sid", "DESC")
             ->range(0,1)
              ->execute()
             ->fetchAll();
  

    foreach ($result as $key => $value) {
       $sid =  $value->sid;
    }
        $node = new stdClass();
        $node->title = $sid+1;
        $node->type = "videos_upload";
        $node->language = LANGUAGE_NONE; 
        $node->uid = TRUE; 
        $node->status = TRUE; 
        $node->promote = FALSE; 
        $node->comment = TRUE;
        $node->path['alias'] = $sid+1;
        $node->metatags[LANGUAGE_NONE]['twitter:player']['value'] = $path_url;
        $node->metatags[LANGUAGE_NONE]['twitter:player:stream']['value'] = $path_url;
       return node_save($node);
}