<?php

/**
 * @file
 * Block Entity
 */


/**
 * Implements hook_block_info().
 */
function nissan_block_info() {
  $blocks['galeria'] = array(
    'info' => t('Galeria'),
    'cache' => DRUPAL_NO_CACHE
  );
  return $blocks;
}


/**
 * Implements hook_theme().
 */
function nissan_theme($existing, $type, $theme, $path) {
 if($type == 'module'){
    return array(
      'nissan_template' => array(
        'variables' => array('var_name'=>NULL),
        'template' => 'templates/real_gallery_videos'
      ),
    );
  }
  return array(); 
}


/**
 * Implements hook_block_view().
 */
function nissan_block_view($delta = '') {
  $block = array();
	 switch ($delta) {
	    case 'galeria':
	   $block['subject'] = t('Galeria');
		 $block['content'] = theme('nissan_template', array('1' =>'1'));
		 break;
	 }
  return $block;
}


/**
 * Implements hook_init().
 */

function nissan_init() {
   Global $base_url;
   drupal_add_js(array('nissan' => array('dominio' => $base_url)), array('type' => 'setting'));
   drupal_add_js(drupal_get_path('module', 'nissan') . '/js/redirect.js');
}